site_name: Fluid - Docs
site_url: https://docs.fluidapi.io/

nav:
    - index.md
    - Conectores: connectors/index.md
    - Sobre: about.md

theme:
    # name: readthedocs
    name: material
    locale: pt_BR
